// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.1
// source: fee_receiver.proto

package feereceiverpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeeReceiver_Generateaddresses_FullMethodName = "/feereceiver.v1.FeeReceiver/Generateaddresses"
	FeeReceiver_Send_FullMethodName              = "/feereceiver.v1.FeeReceiver/Send"
)

// FeeReceiverClient is the client API for FeeReceiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeeReceiverClient interface {
	// Derives one-time stealth fee receivers, 7702-delegates each to the relayer
	// and approves the sweeper for the fee token. Returns the ephemeral public
	// keys to store; the addresses themselves come back from Send.
	Generateaddresses(ctx context.Context, in *PrepareAddressRequest, opts ...grpc.CallOption) (*PrepareAddressResponse, error)
	// Re-derives the receivers from their stored ephemeral keys, confirms the
	// approvals are in place, and returns the addresses with the fee signer's
	// authorization to pass on-chain as `_feeReceiver(s)` / `_data`.
	Send(ctx context.Context, in *VerifyAddressesRequest, opts ...grpc.CallOption) (*VerifyAddressesResponse, error)
}

type feeReceiverClient struct {
	cc grpc.ClientConnInterface
}

func NewFeeReceiverClient(cc grpc.ClientConnInterface) FeeReceiverClient {
	return &feeReceiverClient{cc}
}

func (c *feeReceiverClient) Generateaddresses(ctx context.Context, in *PrepareAddressRequest, opts ...grpc.CallOption) (*PrepareAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareAddressResponse)
	err := c.cc.Invoke(ctx, FeeReceiver_Generateaddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feeReceiverClient) Send(ctx context.Context, in *VerifyAddressesRequest, opts ...grpc.CallOption) (*VerifyAddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAddressesResponse)
	err := c.cc.Invoke(ctx, FeeReceiver_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeeReceiverServer is the server API for FeeReceiver service.
// All implementations must embed UnimplementedFeeReceiverServer
// for forward compatibility.
type FeeReceiverServer interface {
	// Derives one-time stealth fee receivers, 7702-delegates each to the relayer
	// and approves the sweeper for the fee token. Returns the ephemeral public
	// keys to store; the addresses themselves come back from Send.
	Generateaddresses(context.Context, *PrepareAddressRequest) (*PrepareAddressResponse, error)
	// Re-derives the receivers from their stored ephemeral keys, confirms the
	// approvals are in place, and returns the addresses with the fee signer's
	// authorization to pass on-chain as `_feeReceiver(s)` / `_data`.
	Send(context.Context, *VerifyAddressesRequest) (*VerifyAddressesResponse, error)
	mustEmbedUnimplementedFeeReceiverServer()
}

// UnimplementedFeeReceiverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeeReceiverServer struct{}

func (UnimplementedFeeReceiverServer) Generateaddresses(context.Context, *PrepareAddressRequest) (*PrepareAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generateaddresses not implemented")
}
func (UnimplementedFeeReceiverServer) Send(context.Context, *VerifyAddressesRequest) (*VerifyAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedFeeReceiverServer) mustEmbedUnimplementedFeeReceiverServer() {}
func (UnimplementedFeeReceiverServer) testEmbeddedByValue()                     {}

// UnsafeFeeReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeeReceiverServer will
// result in compilation errors.
type UnsafeFeeReceiverServer interface {
	mustEmbedUnimplementedFeeReceiverServer()
}

func RegisterFeeReceiverServer(s grpc.ServiceRegistrar, srv FeeReceiverServer) {
	// If the following call pancis, it indicates UnimplementedFeeReceiverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeeReceiver_ServiceDesc, srv)
}

func _FeeReceiver_Generateaddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeeReceiverServer).Generateaddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeeReceiver_Generateaddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeeReceiverServer).Generateaddresses(ctx, req.(*PrepareAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeeReceiver_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeeReceiverServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeeReceiver_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeeReceiverServer).Send(ctx, req.(*VerifyAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeeReceiver_ServiceDesc is the grpc.ServiceDesc for FeeReceiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeeReceiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "feereceiver.v1.FeeReceiver",
	HandlerType: (*FeeReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generateaddresses",
			Handler:    _FeeReceiver_Generateaddresses_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _FeeReceiver_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fee_receiver.proto",
}
